services:
  cbs-database:
    image: postgres:17
    environment:
      POSTGRES_DB: cbs-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
